let dummyData = {
    "login": "johnoro",
    "id": 34101601,
    "node_id": "MDQ6VXNlcjM0MTAxNjAx",
    "avatar_url": "https://avatars0.githubusercontent.com/u/34101601?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/johnoro",
    "html_url": "https://github.com/johnoro",
    "followers_url": "https://api.github.com/users/johnoro/followers",
    "following_url": "https://api.github.com/users/johnoro/following{/other_user}",
    "gists_url": "https://api.github.com/users/johnoro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/johnoro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/johnoro/subscriptions",
    "organizations_url": "https://api.github.com/users/johnoro/orgs",
    "repos_url": "https://api.github.com/users/johnoro/repos",
    "events_url": "https://api.github.com/users/johnoro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/johnoro/received_events",
    "type": "User",
    "site_admin": false,
    "name": "John O'Rourke",
    "company": "Lambda School",
    "blog": "",
    "location": null,
    "email": null,
    "hireable": true,
    "bio": null,
    "public_repos": 110,
    "public_gists": 1,
    "followers": 30,
    "following": 4,
    "created_at": "2017-11-29T15:54:25Z",
    "updated_at": "2019-08-22T03:22:57Z"
  }

export { dummyData };